---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  become: true
  gather_facts: False
  remote_user: jenkins-slave
  tasks:
  - name: httpd test 
    service:
      name: httpd
      state: started
    register: test

  - name: pass test
    assert:
     that: test.changed == False
