---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  become: true
  tasks:
  - name: httpd test 
    service:
      name: httpd
      state: started
    register: test

  - name: pass test
    assert:
     that: test.changed == False
    #when: test.changed == False

